<?php
/*
<html> 
<head>
<meta http-equiv="Content-Type" content="text/html; charset=WINDOWS-1251" />
<title>EMBRACE YOUR ELEMENT - Element Energy Drinks | All Rights Reserved - 2009</title>
<meta name="medium" content="mult"/>
<meta name="title" content="Element Drinks Presents: Embrace your element"/>
<meta name="description" content="An interactive learning journey through patterns in nature to redefine your true state of matter."/>
<link rel="target_url" href="http://www.embraceyourelement.com/"/>
<script language="javascript">AC_FL_RunContent = 0;</script>
<script type="text/javascript" src="js/swfobject.js"></script>
<script type="text/javascript" src="js/swfmacmousewheel.js"></script>
<script type="text/javascript" src="js/swfaddress.js"></script>
<style type="text/css">
body {
	padding:0px;
	margin:0px;
	height:100%;
	background-color: #000000;
}
#main_div {
	width:100%;
	height:100%;
}
</style>
<script type="text/javascript">
	window.onload = do_resize;
	window.onresize = do_resize;
	function do_resize()
	{
		nav = navigator.appName;
		if (nav != "Netscape")
		{
			var h = document.body.clientHeight;
			var w = document.body.clientWidth;
		}
		else
		{
			var h = window.innerHeight;
			var w = window.innerWidth;
		}
		var hh = ((h > 400) ? "100%" : "400px");
		var ww = ((w > 400) ? "100%" : "400px");
		document.getElementById("main_div").style.height = hh;
		document.getElementById("main_div").style.width = ww;
	}
</script>
</head>
<body><img src="http://www.embraceyourelement.com/fb_pic1.jpg" style="display:none;"><img src="http://www.embraceyourelement.com/fb_pic2.jpg" style="display:none;"><img src="http://www.embraceyourelement.com/fb_pic3.jpg" style="display:none;"><img src="http://www.embraceyourelement.com/fb_pic4.jpg" style="display:none;">
<div id="main_div"></div>
<script type="text/javascript">
// <![CDATA[
	var so = new SWFObject('main.swf', 'website', '100%', '100%', '9', '#000000');
	so.useExpressInstall('js/expressinstall.swf');
	so.addParam('menu', 'false');
	so.addParam('scale', 'noscale');
	so.addParam('wmode', 'window');
	so.addParam('devicefont', 'false');
	so.addParam('allowFullScreen', 'true');
	so.addParam('allowScriptAccess', 'sameDomain');
	so.write('main_div');
	
	var macmousewheel = new SWFMacMouseWheel( so );
// ]]>
</script>
</body>
</html>
*/

#### Generated by the PHP-Nuke Titanium Html to PHP converter ####
global $domain;
OpenTable();
echo "<html>\n";
echo "<head>\n";
echo "<meta http-equiv=\"Content-Type\" content=\"text/html; charset=WINDOWS-1251\" />\n";
echo "<title>EMBRACE YOUR ELEMENT - Element Energy Drinks | All Rights Reserved - 2009</title>\n";
echo "<meta name=\"medium\" content=\"mult\"/>\n";
echo "<meta name=\"title\" content=\"Element Drinks Presents: Embrace your element\"/>\n";
echo "<meta name=\"description\" content=\"An interactive learning journey through patterns in nature to redefine your true state of matter.\"/>\n";
echo "<link rel=\"target_url\" href=\"$domain/\"/>\n";
echo "<script language=\"javascript\">AC_FL_RunContent = 0;</script>\n";
echo "<script type=\"text/javascript\" src=\"modules/Titanium_SandBox/js/swfobject/swfobject.js\"></script>\n";
echo "<script type=\"text/javascript\" src=\"modules/Titanium_SandBox/js/swfmacmousewheel/js/swfmacmousewheel.js\"></script>\n";
echo "<script type=\"text/javascript\" src=\"modules/Titanium_SandBox/js/swfaddress/swfaddress.js\"></script>\n";
echo "<style type=\"text/css\">";

echo "body {\n";
echo "padding:0px;\n";
echo "margin:0px;\n";
echo "height:100%;\n";
echo "background-color: #000000;}\n";

echo "#main_div {\n";
echo "width:100%;\n";
echo "height:100%;}\n";

echo "</style>\n";

echo "<script type=\"text/javascript\">\n";

echo "window.onload = do_resize;\n";
echo "window.onresize = do_resize;\n";

echo "function do_resize(){\n";
     echo "nav = navigator.appName;\n";
     echo "if (nav != \"Netscape\")\n";
     echo "{\n";
         echo "var h = document.body.clientHeight;\n";
         echo "var w = document.body.clientWidth;\n";
     echo "}\n";
echo "else\n";
   echo "{\n";
      echo "var h = window.innerHeight;\n";
      echo "var w = window.innerWidth;\n";
   echo "}\n";

echo "var hh = ((h > 400) ? \"100%\" : \"400px\");\n";
echo "var ww = ((w > 400) ? \"100%\" : \"400px\");\n";
echo "document.getElementById(\"main_div\").style.height = hh;\n";
echo "document.getElementById(\"main_div\").style.width = ww;\n";
echo "}\n";

echo "</script>\n";
echo "</head>\n";
echo "<body><img src=\"$domain/fb_pic1.jpg\" style=\"display:none;\"><img src=\"$domain/fb_pic2.jpg\" style=\"display:none;\"><img src=\"$domain/fb_pic3.jpg\" style=\"display:none;\"><img src=\"$domain/fb_pic4.jpg\" style=\"display:none;\">\n";
echo "<div id=\"main_div\"></div>\n";
echo "<script type=\"text/javascript\">\n";
echo "// <![CDATA[\n";

echo "var so = new SWFObject('modules/Titanium_SandBox/main.swf', 'website', '100%', '100%', '9', '#000000');\n"; 
echo "so.useExpressInstall('modules/Titanium_SandBox/js/swfmacmousewheel/js/expressinstall.swf');\n";
echo "so.addParam('menu', 'false');\n";
echo "so.addParam('scale', 'noscale');\n";
echo "so.addParam('wmode', 'window');\n";
echo "so.addParam('devicefont', 'false');\n";
echo "so.addParam('allowFullScreen', 'true');\n";
echo "so.addParam('allowScriptAccess', 'sameDomain');\n";
echo "so.write('main_div');\n";
echo "var macmousewheel = new SWFMacMouseWheel( so );\n";
echo "// ]]>\n";
echo "</script>\n";
echo "</body>\n";
echo "</html>\n";
CloseTable();
?>















































































































































































