INSERT INTO `#prefix#_blocks` (`bid`, `bkey`, `title`, `content`, `url`, `bposition`, `weight`, `active`, `refresh`, `time`, `blanguage`, `blockfile`, `view`) VALUES
(1, '', 'Evo Main Menu', '', '', 'l', 1, 0, 1800, '0', '', 'block-Modules.php', '1'),
(2, '', 'Search', '', '', 'l', 6, 1, 3600, '', '', 'block-Search.php', '0'),
(3, '', 'Survey', '', '', 'r', 6, 0, 3600, '', '', 'block-Survey.php', '0'),
(4, '', 'Information', '<br /><center><span class=\"content\">\r\n<a href=\"http://phpnuke.org\"><img src=\"images/powered/powered8.jpg\" border=\"0\" alt=\"Powered by PHP-Nuke\" title=\"Powered by PHP-Nuke\" width=\"88\" height=\"31\" /></a>\r\n<br /><br />\r\n<a href=\"http://validator.w3.org/check/referer\"><img src=\"images/html401.gif\" width=\"88\" height=\"31\" alt=\"Valid HTML 4.01!\" title=\"Valid HTML 4.01!\" border=\"0\" /></a>\r\n<br /><br />\r\n<a href=\"http://jigsaw.w3.org/css-validator\"><img src=\"images/css.gif\" width=\"88\" height=\"31\" alt=\"Valid CSS!\" title=\"Valid CSS!\" border=\"0\" /></a></span></center><br />', '', 'r', 7, 0, 0, '', '', '', '0'),
(5, '', 'User Info', '', '', 'r', 0, 1, 0, '', '', 'block-Evo_User_Info.php', '0'),
(6, '', 'Top 10 Links', '', '', 'r', 4, 1, 3600, '0', '', 'block-Titanium_Top10_Links.php', '1'),
(7, '', 'Forums', '', '', 'c', 0, 1, 3600, '0', '', 'block-Titanium_Forums.php', '1'),
(8, '', 'Submissions', '', '', 'l', 2, 0, 0, '', '', 'block-Submissions.php', '4'),
(9, '', 'Link-us', '', '', 'l', 4, 1, 3600, '0', '', 'block-Titanium_Link_Us.php', '1'),
(10, '', 'Shout Box', '', '', 'r', 2, 1, 3600, '0', '', 'block-Titanium_Shout_Box.php', '1'),
(11, '', 'Donations', '', '', 'r', 5, 0, 3600, '0', '', 'block-Donations.php', '0'),
(12, '', 'ECalendar', '', '', 'l', 3, 0, 3600, '0', '', 'block-ECalendar.php', '1'),
(13, '', 'Sentinel Portal Security', '', '', 'd', 0, 1, 3600, '0', '', 'block-Titanium_Sentinel_Center.php', '1'),
(14, '', 'Select Network Theme', '', '', 'r', 1, 1, 3600, '0', '', 'block-Titanium_Themes.php', '1'),
(15, '', 'Honey Pot Protected', '', '', 'l', 5, 1, 3600, '0', '', 'block-Honey_Pot.php', '1'),
(16, '', 'This is exactly how I feel!', '', '', 'c', 2, 0, 3600, '0', '', 'block-Thank_You.php', '1'),
(17, '', 'Portal Menu', '', '', 'l', 0, 1, 3600, '0', '', 'block-Titanium_Portal_Menu.php', '1'),
(18, '', 'Reviews', '', '', 'r', 8, 0, 3600, '0', '', 'block-Reviews.php', '1'),
(19, '', 'Server Information', '', '', 'r', 3, 1, 3600, '0', '', 'block-Portal-Information.php', '1'),
(20, '', 'Visitor Log', '', '', 'c', 1, 1, 3600, '0', '', 'block-Titanium_Visitor_Log_Center.php', '1'),
(25, '', 'Arcade', '', '', 'd', 1, 0, 3600, '0', '', 'block-Titanium_Arcade_Center.php', '1'),
(26, '', 'Visits', '', '', 'l', 7, 1, 3600, '0', '', 'block-Titanium_Total_Hits.php', '1');
