INSERT INTO `#prefix#_evo_userinfo` (`name`, `filename`, `active`, `position`, `image`) VALUES
('Good Afternoon', 'good_afternoon', 1, 1, ''),
('Username', 'username', 0, 2, ''),
('Rank', 'rank', 1, 5, ''),
('Login/logout/register', 'login', 1, 9, ''),
('Current Online', 'online', 1, 19, ''),
('PMs', 'pms', 1, 7, ''),
('Users', 'users', 1, 15, ''),
('Most Ever', 'mostever', 1, 17, ''),
('Members', 'members', 1, 11, ''),
('Avatar', 'avatar', 1, 3, ''),
('Personal Message', 'personal_message', 0, 1, ''),
('Language', 'language', 0, 3, ''),
('Posts', 'posts', 1, 13, ''),
('Break', 'Break', 1, 16, ''),
('Break', 'Break', 1, 14, ''),
('Break', 'Break', 1, 12, ''),
('Break', 'Break', 1, 10, ''),
('Break', 'Break', 1, 8, ''),
('Break', 'Break', 1, 6, ''),
('Break', 'Break', 1, 4, ''),
('Break', 'Break', 1, 2, ''),
('Break', 'Break', 1, 18, '');
