INSERT INTO `#prefix#_nsncb_blocks` (`rid`, `cgid`, `cbid`, `title`, `filename`, `content`, `wtype`, `width`) VALUES
(1, 1, 1, 'Place Holder', '', 'This is only a place holder', 1, 25),
(2, 1, 2, 'Place Holder', '', 'This is only a place holder', 1, 25),
(3, 1, 3, 'Place Holder', '', 'This is only a place holder', 1, 25),
(4, 1, 4, 'Place Holder', '', 'This is only a place holder', 1, 25),
(5, 2, 1, 'Place Holder', '', 'This is only a place holder', 1, 25),
(6, 2, 2, 'Place Holder', '', 'This is only a place holder', 1, 25),
(7, 2, 3, 'Place Holder', '', 'This is only a place holder', 1, 25),
(8, 2, 4, 'Place Holder', '', 'This is only a place holder', 1, 25),
(9, 3, 1, 'Place Holder', '', 'This is only a place holder', 1, 25),
(10, 3, 2, 'Place Holder', '', 'This is only a place holder', 1, 25),
(11, 3, 3, 'Place Holder', '', 'This is only a place holder', 1, 25),
(12, 3, 4, 'Place Holder', '', 'This is only a place holder', 1, 25),
(13, 4, 1, 'Place Holder', '', 'This is only a place holder', 1, 25),
(14, 4, 2, 'Place Holder', '', 'This is only a place holder', 1, 25),
(15, 4, 3, 'Place Holder', '', 'This is only a place holder', 1, 25),
(16, 4, 4, 'Place Holder', '', 'This is only a place holder', 1, 25);
