INSERT INTO `#prefix#_menu_categories` (`id`, `sublevel`, `groupmenu`, `module`, `url`, `url_text`, `image`, `new`, `new_days`, `class`, `bold`, `days`) VALUES
(3584, 0, 1, 'Blogs', '', '', 'tree-greenT.png', '', 3, 'modules', 'on', ''),
(3585, 0, 1, 'Blog_Topics', '', '', 'tree-greenT.png', '', 3, 'modules', 'on', ''),
(3586, 0, 1, 'Blogs_Top', '', '', 'tree-greenT.png', '', 3, 'modules', 'on', ''),
(3587, 0, 1, 'Blog_Archives', '', '', 'tree-greenT.png', '', 3, 'modules', 'on', ''),
(3588, 0, 1, 'Blog_Submit', '', '', 'tree-green-L.png', '', 3, 'modules', 'on', ''),
(3589, 0, 2, 'Forums', '', '', 'tree-lightblueT.png', '', 3, 'modules', 'on', ''),
(3590, 0, 2, 'Groups', '', '', 'tree-lightblueT.png', '', 3, 'modules', 'on', ''),
(3591, 0, 2, 'Members_List', '', '', 'tree-lightblueT.png', '', 3, 'modules', 'on', ''),
(3592, 0, 2, 'File_Repository', '', '', 'tree-lightblueT.png', '', 3, 'modules', 'on', ''),
(3593, 0, 2, 'Shout_Box', '', '', 'tree-lightblueT.png', '', 3, 'modules', 'on', ''),
(3594, 0, 2, 'Loan_Amortization', '', '', 'tree-lightblueT.png', '', 3, 'modules', 'on', ''),
(3595, 0, 2, 'Link_Us', '', '', 'tree-lightblueT.png', '', 3, 'modules', 'on', ''),
(3596, 0, 2, 'Web_Links', '', '', 'tree-lightblueT.png', '', 3, 'modules', 'on', ''),
(3597, 0, 2, 'ECalendar', '', '', 'tree-lightblueT.png', '', 3, 'modules', 'on', ''),
(3598, 0, 2, 'Reviews', '', '', 'tree-lightblueT.png', '', 3, 'modules', 'on', ''),
(3599, 0, 2, 'Surveys', '', '', 'tree-lightblueT.png', '', 3, 'modules', 'on', ''),
(3600, 0, 2, 'Statistics', '', '', 'tree-lightblueT.png', '', 3, 'modules', 'on', ''),
(3601, 0, 2, 'FAQ', '', '', 'tree-lightblueT.png', '', 3, 'modules', 'on', ''),
(3602, 0, 2, 'Feedback', '', '', 'tree-lightblueT.png', '', 3, 'modules', 'on', ''),
(3603, 0, 2, 'Recommend_Us', '', '', 'tree-lightblueT.png', '', 3, 'modules', 'on', ''),
(3604, 0, 2, 'Advertising', '', '', 'tree-lightblueT.png', '', 3, 'modules', 'on', ''),
(3605, 0, 2, 'Google-Site-Map', '', '', 'tree-lightblueT.png', '', 3, 'modules', 'on', ''),
(3606, 0, 2, 'Docs', '', '', 'tree-lightblueT.png', '', 3, 'modules', 'on', ''),
(3607, 0, 2, 'Search', '', '', 'tree-lightblue-L.png', '', 3, 'modules', 'on', ''),
(3608, 0, 3, 'Network', '', '', 'tree-yellowT.png', '', 3, 'modules', 'on', ''),
(3609, 0, 3, 'Network_Projects', '', '', 'tree-yellowT.png', '', 3, 'modules', 'on', ''),
(3610, 0, 3, 'Network_Advertising', '', '', 'tree-yellowT.png', '', 3, 'modules', 'on', ''),
(3611, 0, 3, 'Donations', '', '', 'tree-yellow-L.png', '', 3, 'modules', 'on', ''),
(3612, 0, 4, 'External Link', 'https://www.google.com/webmasters/markup-helper/', 'Markup Helper', 'tree-T.png', '', 3, 'modules', 'on', ''),
(3613, 0, 4, 'External Link', 'https://developers.google.com/youtube/iframe_api_reference', 'YouTube API', 'tree-T.png', '', 3, 'modules', 'on', ''),
(3614, 0, 4, 'External Link', 'https://github.com/googleapis/google-api-php-client', 'api-php-client', 'tree-T.png', '', 3, 'modules', 'on', ''),
(3615, 0, 4, 'External Link', 'https://www.google.com/recaptcha/admin', 'reCAPTCHA', 'tree-T.png', '', 3, 'modules', 'on', ''),
(3616, 0, 4, 'External Link', 'https://google.dev/', 'Dev Profile', 'tree-L.png', '', 3, 'modules', 'on', ''),
(3617, 0, 5, 'HTML_to_PHP', '', '', 'tree-lightblueT.png', '', 3, 'modules', 'on', ''),
(3618, 0, 5, 'Titanium_SandBox', '', '', 'tree-lightblueT.png', '', 3, 'modules', 'on', ''),
(3619, 0, 5, 'External Link', 'https://codecollab.io/app', 'CodeCollab', 'tree-lightblue-L.png', '', 3, 'modules', 'on', ''),
(3620, 0, 6, 'External Link', 'https://codepen.io/ProfessorSamoff/pen/QQrPPy', 'RealTime CSS', 'tree-pinkT.png', '', 3, 'modules', 'on', ''),
(3621, 0, 6, 'CSS_Reference', '', '', 'tree-pinkT.png', '', 3, 'modules', 'on', ''),
(3622, 0, 6, 'CSS_Color_Chart', '', '', 'tree-pink-L.png', '', 3, 'modules', 'on', ''),
(3623, 0, 7, 'External Link', 'https://codecollab.io/', 'CodeCallab', 'tree-yellow-L.png', '', 3, 'modules', 'on', '');
