<?php
/*======================================================================= 
  PHP-Nuke Titanium | Nuke-Evolution Xtreme : PHP-Nuke Web Portal System
 =======================================================================*/


/***************************************************************************
 *                           lang_main_arcade.php
 *                            -------------------
 *
 *   PHPNuke Ported Arcade - http://www.nukearcade.com
 *   Original Arcade Mod phpBB by giefca - http://www.gf-phpbb.com
 *
 ***************************************************************************/

$lang['arcade'] = 'Arcade';
$lang['arcade_game'] = 'Game List';
$lang['toparcade'] = 'Top 5 Games';
$lang['toparcade_five'] = 'Top 5';
$lang['toparcade_players'] = 'The Top 5 Players for Every Game';
$lang['games'] = 'Games';
$lang['game'] = 'Game';
$lang['highscore'] = 'Champion';
$lang['yourbestscore'] = 'Personal Best';
$lang['desc_game'] = 'Description';
$lang['lib_arcade'] = 'Arcade';
$lang['no_record'] = ' NO CHAMPION';
$lang['best_scores'] = 'All Games High Scores';
$lang['best_scores_game'] = 'Current High Scores';
$lang['top5'] = 'Top 5 Games';
$lang['Playing_game'] = "Playing Game";
$lang['Viewing_arcades'] = "Viewing Arcade";
$lang['Viewing_toparcades'] = "Viewing Top Scores";
$lang['statarcade_user'] = 'User Stats';
$lang['statuser'] = 'User Stats';
$lang['statnbset'] = 'Number of plays :';
$lang['stattottime'] = 'Game Time :';
$lang['stathighscore'] = 'Score :';
$lang['statdatehigh'] = 'Last High score on :';
$lang['statposition'] = 'Rank :';
$lang['statmedtime'] = 'Average Time :';
$lang['statminute'] = 'minutes';
$lang['statseconde'] = 'seconds';
$lang['scoreboard'] = 'Current Game High Scores';
$lang['watchingstats'] = 'Watching Stats';
$lang['watchingboard'] = 'Watching Board';
$lang['boardrank'] = 'Rank';
$lang['boardscore'] = 'Score';
$lang['boarddate'] = 'Date';
$lang['boardplayer'] = 'Player';
$lang['Actual_winner'] = 'Current Champion';
$lang['Other_games'] = '<strong>View all games for this category (%s)</strong>';
$lang['game_actual_nbset'] = 'Plays:';
$lang['game_forbidden'] = 'You are not permitted to play this game';
$lang['no_arcade_cat'] = 'There is no category for this..';
$lang['whoisplaying'] = 'Who is Playing?';
$lang['manage_comments'] = 'Manage Your Comments';
$lang['comments'] = 'Comments';
$lang['fav']="My Favorite Games";
$lang['add_fav']='Add this game to favorites';
$lang['del_fav']='Delete this game from favorites';

//ADDED IN V3.0.2
$lang['arcade_comments'] = 'Arcade Comments';
$lang['arcade_comments_full'] = 'Arcade Comments - Full Listing';
$lang['add_edit_comments'] = 'Add or Edit Comments';
$lang['quick_stats'] = 'Quick Stats';
$lang['quick_stats_message'] =     'You currently hold %s highscores.<br />Your favorite game is %s.  You have played it %s times.<br />Your last recorded highscore was on %s playing %s.';
$lang['game_name'] = 'Game Name';
$lang['enter_comment'] = 'Enter Comment';
$lang['arcade_user'] = 'User';
$lang['comments'] = 'Comments';
$lang['comments_champion'] = '<strong>You are the new champion of %s!  Enter your comments below.</strong>';
$lang['congrats'] = 'Congratulations!';
$lang['no_comment'] = 'To return to the Arcade without entering a comment click %s.';
$lang['held_time'] = 'Held Time';
$lang['played_times'] = '<strong>Played</strong> %s Times';
$lang['played_time_total'] = '<strong>Total Time</strong>%s';
$lang['hi_score_on'] = '<strong>Hi-Score Recorded On<br /></strong>%s';

//Language Defintions for the Arcade Header
$lang['heading_top'] = 'Top 10';
$lang['heading_recent'] ='Recent Highscores';
$lang['heading_user'] = 'User Info';
$lang['heading_wins'] = 'Wins';
$lang['heading_last_five'] = 'Last 10 Highscores';
$lang['heading_champ'] = '%s is the champion of %s with a score of %s';
$lang['heading_last_score'] = '%s received a score of %s playing %s on %s';
$lang['heading_stats'] = 'You Have %s Wins';
$lang['heading_plays'] = 'Total Arcade Plays';
$lang['heading_time'] = 'Total Time Playing';
$lang['heading_last_recorded'] = 'Last Recorded Score';

//Language Defintions for the Arcade Search
$lang['search_arcade'] = 'Search Arcade';
$lang['search_game_name'] = 'Game Name';
$lang['search_game_desc'] = 'Game Description';
$lang['search_desc'] = 'Use Wildcards * and ? such as \'yeti*\'';

$lang['games_no_play'] = 'Show Games I haven\'t played';
$lang['games_newest'] = 'Show Newest Games';

//PM on loss of highscore message
$lang['register_pm_subject'] = 'You lost your score in %s...';
$lang['register_pm'] = '<strong>****This message is automatically generated by the site.****</strong><br /><br />Your score of %s in %s has been defeated.  <strong>%s</strong> just scored %s points.  Click %s if you have what it takes to reclaim your title.';

//
// That's all Folks!
// -------------------------------------------------

?>