<?php
/*======================================================================= 
  PHP-Nuke Titanium | Nuke-Evolution Xtreme : PHP-Nuke Web Portal System
 =======================================================================*/


/***************************************************************************
      This file was automatically generated by Admin FAQ Editor
 ***************************************************************************/

/***************************************************************************
 *
 *   This program is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation; either version 2 of the License, or
 *   (at your option) any later version.
 *
 ***************************************************************************/

// 
// To add an entry to your FAQ simply add a line to this file in this format:
// $faq[] = array("question", "answer");
// If you want to separate a section enter $faq[] = array("--","Block heading goes here if wanted");
// Links will be created automatically
//
// DO NOT forget the ; at the end of the line.
// DO NOT put double quotes (") in your FAQ entries, if you absolutely must then escape them ie. \"something\"
//
// The FAQ items will appear on the FAQ page in the same order they are listed in this file
//

$faq[] = array("--", "<strong>Board Rules</strong>");
$faq[] = array("Note", "Please read and accept the following Rules and Guidelines.<br />");
$faq[] = array("01. Welcome to our website", "Our website offers various addons to help improve your experiences while using our website and forums. Please take some time to get familiar with the features and these rules. Thanks a lot and have fun!<br />");
$faq[] = array("02. Search &amp; Forum FAQ", "Before posting, please <a href=\"modules.php?name=Forums&amp;file=search\"><u><strong>SEARCH</strong></u></a> the <a href=\"modules.php?name=Forums&amp;file=index\"><u><strong>Forums</strong></u></a> and take a look at our <a href=\"modules.php?name=Forums&amp;file=faq\"><u><strong>Forum FAQ</strong></u></a> page if you are experience problems with the forums. While doing a search, try to be as specific as possible in your searches.<br />");
$faq[] = array("03. Avoid the following topic titles", "When posting, please avoid to give your topic a title such as:<br />[list]<br />[*] HELP ME PLEASE! <br />[*] I NEED HELP! <br />[*] I have a question. <br />[*] BIG problem! <br />[*] NOOB needs help! <br />[*] Problems <br />[*] URGENT! <br />[*] HELP ME PLEASE.<br />[*] NEED HELP FAST.[/list]<br />or ANYTHING like the above! <br /><br />Please try to be as specific as possible in choosing a title for your post. This not only helps us to get an idea of the content, it also helps to find a topic faster which should result in quicker replies.<br />");
$faq[] = array("04. Help us, help you. When you post, post as much information as you can", "When you like to post something and ask for information or help, please try to give as much information as possible in order to make it easier for us to try to give you an answer.<br />");
$faq[] = array("05. Use similar existing topics if possible", "Please try to only start new topics as necessary. If a similar topic exists, please post in it. It will move that topic to the top of the list and your post will be seen. It also is a good idea since there may be a few users subscribed to that posts notification.<br />");
$faq[] = array("06. Post your topic in the respective forum", "Please post your topic in the most appropriate forum. This not only will help us to find and answer your problems faster, it also helps to have an organized forum on our website and thus will help everyone to find what they are looking for.");
$faq[] = array("07. Reporting Problems / Bugs and other comments", "If you come across a problem or bug while browsing our website, please report it in the appropriate forum, try to include the error message shown and try to describe what may have caused the error. Feel free to request further features or just give us feedback if you like. Thanks.<br />");
$faq[] = array("08. Watch your language", "Foul, offensive, racist or crude language as well as swearing is not welcome. You have been warned!<br />");
$faq[] = array("09. Flames, Attacks &amp; Off Topic Comments", "No flames, personal attacks or contentious off topic comments: The idea is to make this a pleasant environment for everyone.<br />");
$faq[] = array("10. Misunderstandings", "Allow for the possibility of misunderstandings, and be patient if someone asks for an explanation of what seems to be obvious.<br />");
$faq[] = array("11. Censorship &amp; violate these rules", "Debate about everything, even when heated, is encouraged. This is not about censorship. However, while we do not and cannot police every post, we will delete posts coming to our attention that we believe violate these rules.<br />");
$faq[] = array("12. Multiple &amp; duplicated Topics / Posts", "Posting the same message to multiple boards and / or topics is not allowed. Multiple &amp; duplicated posts will be deleted. Furthermore, posting a topic 2 or more times will not get you a quicker response... it will more than likely get no response.<br />");
$faq[] = array("13. Warez", "No copyrighted or trademarked (warez) material will be tolerated.<br />");
$faq[] = array("14. Advertisement", "Commercial advertisements are not welcomed on our website. There are other websites for that. Thanks.<br />");

$faq[] = array("--", "<strong>Other Rules</strong>");
$faq[] = array("Note", "Please read and accept the following global Rule and Guidelines about contacting administrators / webmasters and abuse of Private Message system.<br />");
$faq[] = array("01. No support via e-mail, Instant Messaging Systems or Private Messaging", "Please do not contact the administrators, webmasters, and moderators by e-mail, Instant Messaging Systems like MSN, ICQ, Yahoo etc. or Private Messaging with questions [b]UNLESS[/b] they have told you to do so! Uninvited private messages and privately addressed questions will be most likely ignored! Use our forums to get in touch with them.<br />");
$faq[] = array("02. Spamming Via Private Message System", "Sending avertisement throughout the Private Message System, is not allowed. We do monitor the Private Message too see if this rule is followed. If we catch anybody sending advertisements to our members, or if it gets reported, your IP gets banned without further notice, and forever. [b]NO WARNING WILL BE GIVEN[/b].<br />");

?>