<?php
#### Generated by Block Creator by Disipal Site (www.disipal.net) ###
if (eregi("block-DDFlashNav.php",$PHP_SELF)) {
    Header("Location: index.php");
    die();
}
$content  =  "<html xmlns=\"http://www.w3.org/1999/xhtml\" xml:lang=\"en\" lang=\"en\">";
$content  .= "<head>";
$content  .= "<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\" />";
$content  .= "<title>DD Flash Nav</title>";
$content  .= "</head>";
$content  .= "<body bgcolor=\"#0B121A\">";
$content  .= "<!--url's used in the movie-->";
$content  .= "<!--text used in the movie-->";
$content  .= "<center>";
global $prefix, $dbi, $admin;


/* Make dropdown or block style full selection menu - NOTE: inactive modules only viewable by Admin */
$content  .= "<object classid=\"clsid:d27cdb6e-ae6d-11cf-96b8-444553540000\" codebase=\"http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=7,0,0,0\" width=\"134\" height=\"312\" id=\"tribalblock\" align=\"middle\">";
$content  .= "<param name=\"allowScriptAccess\" value=\"sameDomain\" />";
$content  .= "<param name=\"movie\" value=\"includes/nav/FlashNav.swf\" />";
$content  .= "<param name=\"quality\" value=\"high\" />";
$content  .= "<param name=\"bgcolor\" value=\"#18222E\" />";
$content  .= "<embed src=\"includes/nav/FlashNav.swf\" quality=\"high\" bgcolor=\"#18222E\" width=\"134\" height=\"312\" name=\"FlashNav\" align=\"middle\" allowScriptAccess=\"sameDomain\" type=\"application/x-shockwave-flash\" pluginspage=\"http://www.macromedia.com/go/getflashplayer\" />";
$content  .= "</object>";
if ($dropDown == 0){
    $content .= "<CENTER><br><TABLE BORDER=0 CELLPADDING=0 CELLSPACING=0><TR><FORM METHOD=POST ACTION=\"modules.php\"><TD><SELECT NAME=\"name\" onChange=\"top.location.href=this.options[this.selectedIndex].value\"><OPTION VALUE=\"\">Full Selection";
    }	else {
	$content .= "<CENTER><br><TABLE BORDER=0 CELLPADDING=0 CELLSPACING=0><TR><FORM METHOD=POST ACTION=\"modules.php\"><TD><SELECT NAME=\"name\" MULTIPLE SIZE=\"$row2show\" onChange=\"top.location.href=this.options[this.selectedIndex].value\"><OPTION VALUE=\"\">Full Selection";
	}

$content .= "<OPTION VALUE=\"\">---------------\n";
$result = sql_query("select title, custom_title, view from ".$prefix."_modules where active='1' AND title!='$def_module' AND inmenu='1' ORDER BY title ASC", $dbi);
while(list($m_title, $custom_title, $view) = sql_fetch_row($result, $dbi)) {
    $m_title2 = ereg_replace("_", " ", $m_title);
    if ($custom_title != "") {
	$m_title2 = $custom_title;
	}
    if ($m_title != $main_module) {
    if ((is_admin($admin) AND $view == 2) OR $view != 2) {
	$content .= "<OPTION VALUE=\"modules.php?name=$m_title\">$m_title2\n";
	}
    }
}
/* If you're Admin you and only you can see Inactive modules and test it */
/* If you copied a new module is the /modules/ directory, it will be added to the database */
    
    if (is_admin($admin)) {
	$handle=opendir('modules');
	while ($file = readdir($handle)) {
	    if ( (!ereg("[.]",$file)) ) {
		$modlist .= "$file ";
	    }
	}
	closedir($handle);
	$modlist = explode(" ", $modlist);
	sort($modlist);
	for ($i=0; $i < sizeof($modlist); $i++) {
	    if($modlist[$i] != "") {
		$result = sql_query("select mid from ".$prefix."_modules where title='$modlist[$i]'", $dbi);
		list ($mid) = sql_fetch_row($result, $dbi);
		if ($mid == "") {
		    sql_query("insert into ".$prefix."_modules values (NULL, '$modlist[$i]', '$modlist[$i]', '0', '0', '1')", $dbi);
		}
	    }
	}
	
	$content .= "<OPTION VALUE=\"\">---------------\n";
    $content .= "<OPTION VALUE=\"\">"._INVISIBLEMODULES."\n";
    //$content .= "<OPTION VALUE=\"\">"._ACTIVEBUTNOTSEE."\n";
    $content .= "<OPTION VALUE=\"\">---------------\n";
    $result = sql_query("select title, custom_title from ".$prefix."_modules where active='1' AND inmenu='0' ORDER BY title ASC", $dbi);
    while(list($mn_title, $custom_title) = sql_fetch_row($result, $dbi)) {
	$mn_title2 = ereg_replace("_", " ", $mn_title);
	if ($custom_title != "") {
	    $mn_title2 = $custom_title;
	}
    if ($mn_title2 != "") {
	$content .= "<OPTION VALUE=\"modules.php?name=$mn_title\">$mn_title2\n";
	$dummy = 1;
    } else {
    $a = 1;
    }
    }
    if ($a = 1 AND $dummy != 1) {
        $content .= "<OPTION VALUE=\"\">"._NONE."\n";
	}
	
    $content .= "<OPTION VALUE=\"\">---------------\n";
    $content .= "<OPTION VALUE=\"\">"._NOACTIVEMODULES."\n";
    //$content .= "<OPTION VALUE=\"\">"._FORADMINTESTS."\n";
    $content .= "<OPTION VALUE=\"\">---------------\n";
    $result = sql_query("select title, custom_title from ".$prefix."_modules where active='0' ORDER BY title ASC", $dbi);
    while(list($mn_title, $custom_title) = sql_fetch_row($result, $dbi)) {
	$mn_title2 = ereg_replace("_", " ", $mn_title);
	if ($custom_title != "") {
	    $mn_title2 = $custom_title;
	}
    if ($mn_title2 != "") {
	$content .= "<OPTION VALUE=\"modules.php?name=$mn_title\">$mn_title2\n";
	$dummy = 1;
    } else {
    $a = 1;
    }
    }
    if ($a = 1 AND $dummy != 1) {
        $content .= "<OPTION VALUE=\"\">"._NONE."\n";
	}
}
$content .= "</SELECT></TD></TR></FORM></TABLE></CENTER>";

/* Search feature */
if ($viewSearch == 0){
    $content .= "<center><TABLE BORDER=0 CELLPADDING=0 CELLSPACING=0><TR><form action=\"modules.php?name=Search\" method=\"post\">";
    $content .= "<br><center><input type=\"text\" onfocus=\"value=''\" value=\"Site Search\" name=\"query\" size=\"20\"></center>";
    $content .= "</TD></TR></form></TABLE></center>";
    }	else {
	return;
	}
$content  .= "</center>";
$content  .= "</body>";
$content  .= "</html>";
?>